# Generated by Django 4.2.4 on 2023-10-29 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0005_imagethumbnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imagethumbnail",
            old_name="image",
            new_name="image_thumb",
        ),
    ]
