# Generated by Django 4.2.4 on 2023-10-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_tier_built_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='built_in',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=10),
        ),
    ]
