# Generated by Django 4.2.4 on 2023-11-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_remove_tier_thumbnail_sizes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagethumbnail',
            name='thumbnail_size',
        ),
    ]
