# Generated by Django 4.2.4 on 2023-11-02 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0016_customtier_image_thumb"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customtier",
            name="image_thumb",
        ),
        migrations.AddField(
            model_name="imagethumbnail",
            name="custom_tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="images.customtier",
            ),
        ),
        migrations.AddField(
            model_name="imagethumbnail",
            name="original_image_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="customtier",
            name="thumbnail_sizes",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
