# Generated by Django 4.2.4 on 2023-11-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0017_remove_customtier_image_thumb_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customtier",
            name="thumbnail_sizes",
        ),
        migrations.RemoveField(
            model_name="imagethumbnail",
            name="custom_tier",
        ),
        migrations.RemoveField(
            model_name="imagethumbnail",
            name="original_image_link",
        ),
        migrations.AddField(
            model_name="customtier",
            name="thumbnail_height",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customtier",
            name="thumbnail_width",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
