# Generated by Django 4.2.4 on 2023-11-02 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0018_remove_customtier_thumbnail_sizes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagethumbnail",
            name="custom_tier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="images.customtier",
            ),
            preserve_default=False,
        ),
    ]
