# Generated by Django 4.2.4 on 2023-11-02 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0019_imagethumbnail_custom_tier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagethumbnail",
            name="custom_tier",
        ),
    ]
