# Generated by Django 4.2.4 on 2023-11-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0024_alter_accounttier_thumbnail_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttier",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
