name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v0
      with:
        service_account_key: ${{ secrets.GC_KEY_JSON }}
        project_id: <your-project-id>

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up environment variables
      run: |
        echo "GS_BUCKET_NAME=${{ secrets.GS_BUCKET_NAME }}" >> $GITHUB_ENV
        echo "GOOGLE_CLOUD_STORAGE_URL=http://storage.googleapis.com/${{ secrets.GS_BUCKET_NAME }}" >> $GITHUB_ENV

    - name: Run tests
      run: |
        export DJANGO_SETTINGS_MODULE=ImageApp.test_settings
        export DB_NAME=test_db
        export DB_USER=test_user
        export DB_PASSWORD=test_password
        export DB_HOST=db
        export DB_PORT=5432
        python manage.py test
      env:
        POSTGRES_DB: test_db
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_password

    - name: Run linters
      run: |
        pip install flake8
        flake .

    - name: Check code formatting
      run: |
        pip install black
        black --check .

    - name: Check security vulnerabilities
      run: |
        pip install bandit
        bandit -r .
