name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up environment variables from ENV_FILE
      run: |
        echo "${{ secrets.ENV_FILE }}" > dev.env
        export $(cat dev.env | xargs)
        echo "DJANGO_SETTINGS_MODULE=ImageApp.test_settings" >> $GITHUB_ENV

    - name: Run tests
      run: |
        python manage.py test
      env:
        POSTGRES_DB: ${{ secrets.DB_NAME }}
        POSTGRES_USER: ${{ secrets.DB_USER }}
        POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        GC_BUCKET_NAME: ${{ secrets.GS_BUCKET_NAME }}

    - name: Run linters
      run: |
        pip install flake8
        flake8 .

    - name: Check code formatting
      run: |
        pip install black
        black --check .

    - name: Check security vulnerabilities
      run: |
        pip install bandit
        bandit -r .
