name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Install PostgreSQL client
      run: |
        if ! command -v psql &> /dev/null; then
          apt-get update
          apt-get install --yes postgresql-client
        fi

    - name: Query database
      run: psql -h postgres -d test_db -U test_user -c 'SELECT 1;'
      env:
        PGPASSWORD: test_password

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
          export DB_NAME=test_tb
          export DB_USER=test_user
          export DB_PASSWORD=test_password
          export DB_HOST=db
          export DB_PORT=5432
          python manage.py run pytest --settings=ImageApp.test_settings

    - name: Run linters
      run: |
        pip install flake8
        flake .

    - name: Check code formatting
      run: |
        pip install black
        black --check .

    - name: Check security vulnerabilities
      run: |
        pip install bandit
        bandit -r .